# Stick
#
# Copyright Â© 2017-2019 Jeron Aldaron Lau.
# Dual-licensed under either the MIT License or the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_BSL.txt or copy at https://www.boost.org/LICENSE_1_0.txt, and
# accompanying file LICENSE_MIT.txt or copy at https://opensource.org/licenses/MIT)

[package]
name = "stick"
version = "0.7.0"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2018"

license = "MIT / BSL-1.0"
documentation = "https://docs.rs/stick"
homepage = "https://jeronaldaron.github.io/stick"
repository = "https://github.com/JeronAldaron/stick"

readme = "README.md"
description = "Get input from joysticks, gamepads, and other controllers"
keywords = [
	"interface", "joystick", "gamepad", "platform-agnostic", "controller"
]
categories = ["hardware-support"]

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.png", "icon.ico"
]

[dependencies]
