name = "Flydigi Apex 2 (Wired)"
type = "gamepad"

[remap]
# Sticks
JoyZ = "CamX"
CamZ = "CamY"

# Wheel
Brake = "ActionWheelX"
Gas = "ActionWheelY"

# Face buttons flipped in function
ActionV = "ActionH"
ActionH = "ActionV"

# Rear buttons
15 = "ActionL" # Left Nub, diagonally between and bumpers
14 = "ActionR" # Right Nub

# Underside
11 = "PinkyLeft" # Right Under
# Right Grip already dubbed PinkyRight
13 = "PaddleLeft" # Left Under
12 = "PaddleRight" # Left Grip
