name = 'Thrustmaster T-16000M Flight Stick'
type = 'Flightstick'

[[button]]
code = 0
event = 'ActionA'

[[button]]
code = 1
event = 'ActionV'

[[button]]
code = 2
event = 'ActionH'

[[button]]
code = 3
event = 'ActionB'

[[button]]
code = 4
event = 'Action0'

[[button]]
code = 5
event = 'Action1'

[[button]]
code = 6
event = 'Action2'

[[button]]
code = 7
event = 'Action3'

[[button]]
code = 8
event = 'Action4'

[[button]]
code = 9
event = 'Action5'

[[button]]
code = 10
event = 'Action6'

[[button]]
code = 11
event = 'Action7'

[[button]]
code = 12
event = 'Action8'

[[button]]
code = 13
event = 'Action9'

[[button]]
code = 14
event = 'Action10'

[[button]]
code = 15
event = 'Action11'

[[button]]
code = 256
event = 'DpadUp'

[[button]]
code = 257
event = 'DpadDown'

[[button]]
code = 258
event = 'DpadLeft'

[[button]]
code = 259
event = 'DpadRight'

[[axis]]
code = 0
event = 'JoyX'

[[axis]]
code = 1
event = 'JoyY'

[[axis]]
code = 5
event = 'JoyZ'

[[three_way]]
code = 16
neg = 'DpadLeft'
pos = 'DpadRight'

[[three_way]]
code = 17
neg = 'DpadUp'
pos = 'DpadDown'
